CREATE TABLE clientes(
codigo INT NOT NULL PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL,
cpf VARCHAR(14) NOT NULL,
sexo VARCHAR(20) NOT NULL,
usuario VARCHAR(100) NOT NULL,
senha VARCHAR(20) NOT NULL
);